In [ ]:
#OneHotEncoding 

In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv(r'C:\Users\Naveen s kamatagi\Downloads\4-hour-course-xl-files\IndividualDetails11.csv',encoding='latin1')

In [3]:
dataset.head(4)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15-03-2020,"Travelled from Austria, Italy"


In [4]:
en_data=dataset[["gender"]]

In [5]:
pd.get_dummies(en_data)

,gender_F,gender_M
0,True,False
1,False,False
2,False,False
3,False,True
4,False,True
...,...,...
28177,False,False
28178,False,False
28179,False,False
28180,False,False


In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
ohe=OneHotEncoder()

In [8]:
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 28182 stored elements and shape (28182, 3)>

In [9]:
ohe.fit_transform(en_data).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(28182, 3))

In [10]:
ar=ohe.fit_transform(en_data).toarray()


In [11]:
pd.DataFrame(ar,columns=["gender_F","gender_M","gender_o"])

,gender_F,gender_M,gender_o
0,1.0,0.0,0.0
1,0.0,0.0,1.0
2,0.0,0.0,1.0
3,0.0,1.0,0.0
4,0.0,1.0,0.0
...,...,...,...
28177,0.0,0.0,1.0
28178,0.0,0.0,1.0
28179,0.0,0.0,1.0
28180,0.0,0.0,1.0


In [12]:
#label Encoding

In [15]:
df=pd.DataFrame({"names":["cat","dog","pig","blck","zibra"]})

In [13]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()
df["en_data"]=le.fit_transform(df["names"])

In [19]:
 df

,names,en_data
0,cat,1
1,dog,2
2,pig,3
3,blck,0
4,zibra,4


In [27]:
dataset["detected_city"].unique()

array([471,  11, 212, 122, 169, 178, 151,   4, 511, 185, 141, 488, 256,
       201, 415, 479, 184,  50, 206, 392,  14, 245, 226,  93, 104, 301,
       384, 313, 344, 264, 197, 111, 493, 341, 468,   7, 463, 199, 367,
       336, 508, 305,  30, 110, 409, 198, 276,  63, 424, 209, 260, 275,
       348, 234,  51, 138,  95, 445, 224, 189, 116,  83, 485, 227, 351,
       404, 258,  39, 126, 407, 456, 502, 412,  25, 139,  48, 294, 105,
       177, 350,   6, 490,  56, 127, 365, 203, 176, 210, 506, 153, 147,
       362, 429, 132, 299, 380, 337, 136, 308, 448, 121,  59, 257, 405,
       499, 148, 492, 164, 303, 302, 106, 304, 372,  60, 242, 247,  52,
       498, 193, 230,   1, 474, 503, 442, 462, 495, 359,  36, 422, 447,
       128, 207, 383, 476, 273, 186, 217, 428, 223, 171, 394, 284,  98,
       388, 395, 220, 231,  82,  47, 334, 381, 450, 423, 285, 172, 484,
       190, 483, 265, 120, 408, 505, 142, 339,  68,  55, 349,  35, 397,
       119, 437,  21,  40, 480, 391, 358, 109, 360,  18, 289, 24

In [22]:
la=LabelEncoder()
la.fit(dataset["detected_city"])

LabelEncoder()

In [23]:
la.transform(dataset["detected_city"])

array([471,  11, 212, ..., 511, 511, 511], shape=(28182,))

In [26]:
dataset["detected_city"]=la.transform(dataset["detected_city"])

In [28]:
#Ordinary Encoding

In [30]:
dn=pd.DataFrame({"size":["s","m","l","xl","s","m","l","xl","s","m"]})

In [31]:
dn

,size
0,s
1,m
2,l
3,xl
4,s
5,m
6,l
7,xl
8,s
9,m


In [32]:
ord_data=[["s","m","l","xl"]]

In [33]:
from sklearn.preprocessing import OrdinalEncoder

In [34]:
oe=OrdinalEncoder()
oe.fit(dn[["size"]])

,categories,'auto'
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [35]:
oe.transform(dn[["size"]])

array([[2.],
       [1.],
       [0.],
       [3.],
       [2.],
       [1.],
       [0.],
       [3.],
       [2.],
       [1.]])

In [36]:
dn["size_en"]=oe.transform(dn[["size"]])

In [37]:
dn

,size,size_en
0,s,2.0
1,m,1.0
2,l,0.0
3,xl,3.0
4,s,2.0
5,m,1.0
6,l,0.0
7,xl,3.0
8,s,2.0
9,m,1.0


In [38]:
#Map Function

In [39]:
ord_data1={"s":0,"m":2,"l":5,"xl":3}

In [40]:
dn["size"].map(ord_data1)

0    0
1    2
2    5
3    3
4    0
5    2
6    5
7    3
8    0
9    2
Name: size, dtype: int64

In [41]:
dn["size_en_map"]=dn["size"].map(ord_data1)

In [42]:
dn

,size,size_en,size_en_map
0,s,2.0,0
1,m,1.0,2
2,l,0.0,5
3,xl,3.0,3
4,s,2.0,0
5,m,1.0,2
6,l,0.0,5
7,xl,3.0,3
8,s,2.0,0
9,m,1.0,2


In [43]:
#using real data perform the ordinal Encoding

In [46]:
dataset["current_status"].unique()

array(['Recovered', 'Hospitalized', 'Deceased', 'Migrated'], dtype=object)

In [47]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28182 entries, 0 to 28181
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   id                  28182 non-null  int64 
 1   government_id       2997 non-null   object
 2   diagnosed_date      28182 non-null  object
 3   age                 2346 non-null   object
 4   gender              5313 non-null   object
 5   detected_city       28182 non-null  int64 
 6   detected_district   21198 non-null  object
 7   detected_state      28182 non-null  object
 8   nationality         2709 non-null   object
 9   current_status      28182 non-null  object
 10  status_change_date  27780 non-null  object
 11  notes               26847 non-null  object
dtypes: int64(2), object(10)
memory usage: 2.6+ MB


In [48]:
en_data_ordinal=[["Recovered","Hospitalized","Deceased","Migrated"]]

In [50]:
one=OrdinalEncoder(categories=en_data_ordinal)

In [52]:
dataset["current_status"]=one.fit_transform(dataset[["current_status"]])

In [53]:
dataset

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,471,Thrissur,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,11,Alappuzha,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,212,Kasaragod,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,122,East Delhi,Delhi,India,0.0,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,169,Hyderabad,Telangana,India,0.0,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
28177,28178,NaN,22-04-2020,NaN,NaN,511,NaN,Maharashtra,NaN,1.0,NaN,Correction for district count
28178,28179,NaN,24-04-2020,NaN,NaN,511,Nagpur,Maharashtra,NaN,1.0,NaN,Correction for district count
28179,28180,NaN,24-04-2020,NaN,NaN,511,NaN,Maharashtra,NaN,1.0,NaN,Correction for district count
28180,28181,NaN,25-04-2020,NaN,NaN,511,Nagpur,Maharashtra,NaN,1.0,NaN,Correction for district count


In [54]:
dataset.head(5)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30-01-2020,20,F,471,Thrissur,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
1,1,KL-AL-P1,02-02-2020,NaN,NaN,11,Alappuzha,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
2,2,KL-KS-P1,03-02-2020,NaN,NaN,212,Kasaragod,Kerala,India,0.0,14-02-2020,Travelled from Wuhan
3,3,DL-P1,02-03-2020,45,M,122,East Delhi,Delhi,India,0.0,15-03-2020,"Travelled from Austria, Italy"
4,4,TS-P1,02-03-2020,24,M,169,Hyderabad,Telangana,India,0.0,02-03-2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
